// stencil-in-react/src/App.js
import React, { Component } from 'react';
import './App.css';

class App extends Component {

  state = {
    isOpen: true
  }

  handleButtonPress = () => {
    this.setState({
      isOpen: !this.state.isOpen
    })
  }



  render() {
    return (
      <div className="App">
        <header className="App-header">
          <p>
            Edit <code>src/App.js</code> and save to reload.
          </p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
        <br />
        <cl-weather-card
          location="Toronto"
          src="http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0011_light_snow_showers.png"
          temperature="-11°"
          details="Heavy Rain"
        ></cl-weather-card>
        <br />
        <cl-expansion-panel is-open={this.state.isOpen}></cl-expansion-panel>
        <button onClick={this.handleButtonPress}>toggle</button>
      </div>
    );
  }
}

export default App;

// stencil-in-angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'stencil-in-angular';

  isOpen = false;

  handleTogglePanel() {
    console.log('toggle panel');
    this.isOpen = !this.isOpen;
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <h1>
    Welcome to {{ title }}!
  </h1>
  <img width="300" alt="Angular Logo" src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg==">
</div>
<cl-weather-card
  location="Toronto"
  src="http://cdn.worldweatheronline.net/images/wsymbols01_png_64/wsymbol_0011_light_snow_showers.png"
  temperature="-11°"
  details="Heavy Rain"
  ></cl-weather-card>
<br />
<cl-expansion-panel [is-open]="isOpen"></cl-expansion-panel>
<button (click)="handleTogglePanel()">Toggle Panel</button>

<router-outlet></router-outlet>
